apiVersion: apps/v1
kind: Deployment
metadata:
  name: matcher
  labels:
    app: matcher
spec:
  replicas: 3
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: matcher
  template:
    metadata:
      labels:
        app: matcher
    spec:
      containers:
        - name: matcher
          image: hkccr.ccs.tencentyun.com/tke_cluster/tke_cluster
          imagePullPolicy: Always
          #          args:
          #            - "-DBUser "
          #            - "-DBPassword "
          #            - "-Host mongodb"
          #            - "-Port "
          ports:
            - containerPort: 8889
              protocol: UDP
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      nodeSelector:
        environment: dev