apiVersion: v1
kind: Service
metadata:
  name: matcher
spec:
  type: ClusterIP
  ports:
    - port: 8889
      targetPort: 8889
      nodePort: 32002
      protocol: UDP
  selector:
    app: matcher
  sessionAffinity: ClientIP
#  sessionAffinityConfig:
#    clientIP:
#      timeoutSeconds: 3600