apiVersion: v1
kind: Service
metadata:
  name: matcher
  annotations:
    service.cloud.tencent.com/direct-access: "true"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - port: 8889
      targetPort: 8889
      nodePort: 32002
      protocol: UDP
  selector:
    app: matcher
  sessionAffinity: ClientIP
#  sessionAffinityConfig:
#    clientIP:
#      timeoutSeconds: 3600