// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: msgenum.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MSG_TYPE int32

const (
	MSG_TYPE_NOTIFY   MSG_TYPE = 0 //通知类型
	MSG_TYPE_REQUEST  MSG_TYPE = 1 //请求类型
	MSG_TYPE_RESPONSE MSG_TYPE = 2 //答复类型
)

// Enum value maps for MSG_TYPE.
var (
	MSG_TYPE_name = map[int32]string{
		0: "NOTIFY",
		1: "REQUEST",
		2: "RESPONSE",
	}
	MSG_TYPE_value = map[string]int32{
		"NOTIFY":   0,
		"REQUEST":  1,
		"RESPONSE": 2,
	}
)

func (x MSG_TYPE) Enum() *MSG_TYPE {
	p := new(MSG_TYPE)
	*p = x
	return p
}

func (x MSG_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MSG_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_msgenum_proto_enumTypes[0].Descriptor()
}

func (MSG_TYPE) Type() protoreflect.EnumType {
	return &file_msgenum_proto_enumTypes[0]
}

func (x MSG_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MSG_TYPE.Descriptor instead.
func (MSG_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_msgenum_proto_rawDescGZIP(), []int{0}
}

type GAME_MSG_CODE int32

const (
	GAME_MSG_CODE_PLAYER_MATCHING_REQUEST  GAME_MSG_CODE = 0
	GAME_MSG_CODE_PLAYER_MATCHING_RESPONSE GAME_MSG_CODE = 1
)

// Enum value maps for GAME_MSG_CODE.
var (
	GAME_MSG_CODE_name = map[int32]string{
		0: "PLAYER_MATCHING_REQUEST",
		1: "PLAYER_MATCHING_RESPONSE",
	}
	GAME_MSG_CODE_value = map[string]int32{
		"PLAYER_MATCHING_REQUEST":  0,
		"PLAYER_MATCHING_RESPONSE": 1,
	}
)

func (x GAME_MSG_CODE) Enum() *GAME_MSG_CODE {
	p := new(GAME_MSG_CODE)
	*p = x
	return p
}

func (x GAME_MSG_CODE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GAME_MSG_CODE) Descriptor() protoreflect.EnumDescriptor {
	return file_msgenum_proto_enumTypes[1].Descriptor()
}

func (GAME_MSG_CODE) Type() protoreflect.EnumType {
	return &file_msgenum_proto_enumTypes[1]
}

func (x GAME_MSG_CODE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GAME_MSG_CODE.Descriptor instead.
func (GAME_MSG_CODE) EnumDescriptor() ([]byte, []int) {
	return file_msgenum_proto_rawDescGZIP(), []int{1}
}

// response的result枚举
type RESULT_TYPE int32

const (
	RESULT_TYPE_SUCCESS RESULT_TYPE = 0 //成功
	RESULT_TYPE_FAIL    RESULT_TYPE = 1 //失败
)

// Enum value maps for RESULT_TYPE.
var (
	RESULT_TYPE_name = map[int32]string{
		0: "SUCCESS",
		1: "FAIL",
	}
	RESULT_TYPE_value = map[string]int32{
		"SUCCESS": 0,
		"FAIL":    1,
	}
)

func (x RESULT_TYPE) Enum() *RESULT_TYPE {
	p := new(RESULT_TYPE)
	*p = x
	return p
}

func (x RESULT_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RESULT_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_msgenum_proto_enumTypes[2].Descriptor()
}

func (RESULT_TYPE) Type() protoreflect.EnumType {
	return &file_msgenum_proto_enumTypes[2]
}

func (x RESULT_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RESULT_TYPE.Descriptor instead.
func (RESULT_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_msgenum_proto_rawDescGZIP(), []int{2}
}

var File_msgenum_proto protoreflect.FileDescriptor

var file_msgenum_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x73, 0x67, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0a, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x31, 0x0a, 0x08, 0x4d,
	0x53, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x4f, 0x54, 0x49, 0x46,
	0x59, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0x01,
	0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x10, 0x02, 0x2a, 0x4a,
	0x0a, 0x0d, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x4d, 0x53, 0x47, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x12,
	0x1b, 0x0a, 0x17, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x49,
	0x4e, 0x47, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0x00, 0x12, 0x1c, 0x0a, 0x18,
	0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x49, 0x4e, 0x47, 0x5f,
	0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x10, 0x01, 0x2a, 0x24, 0x0a, 0x0b, 0x52, 0x45,
	0x53, 0x55, 0x4c, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43,
	0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x41, 0x49, 0x4c, 0x10, 0x01,
	0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msgenum_proto_rawDescOnce sync.Once
	file_msgenum_proto_rawDescData = file_msgenum_proto_rawDesc
)

func file_msgenum_proto_rawDescGZIP() []byte {
	file_msgenum_proto_rawDescOnce.Do(func() {
		file_msgenum_proto_rawDescData = protoimpl.X.CompressGZIP(file_msgenum_proto_rawDescData)
	})
	return file_msgenum_proto_rawDescData
}

var file_msgenum_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_msgenum_proto_goTypes = []interface{}{
	(MSG_TYPE)(0),      // 0: matchproto.MSG_TYPE
	(GAME_MSG_CODE)(0), // 1: matchproto.GAME_MSG_CODE
	(RESULT_TYPE)(0),   // 2: matchproto.RESULT_TYPE
}
var file_msgenum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_msgenum_proto_init() }
func file_msgenum_proto_init() {
	if File_msgenum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msgenum_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msgenum_proto_goTypes,
		DependencyIndexes: file_msgenum_proto_depIdxs,
		EnumInfos:         file_msgenum_proto_enumTypes,
	}.Build()
	File_msgenum_proto = out.File
	file_msgenum_proto_rawDesc = nil
	file_msgenum_proto_goTypes = nil
	file_msgenum_proto_depIdxs = nil
}
